sudo: false
os:
- linux
language: node_js
node_js:
- 8

env:
  global:
    secure: [VS_TOKEN=<Visual Studio Auth Token>]

install:
- npm install;

script:
- npm run compile
- npm test --silent

before_deploy:
- npm install -g vsce;
- vsce package;

deploy:
- provider: releases
  api_key:
    secure: [GITHUB_AUTH_TOKEN]
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: spgennard/vscode_cobol
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: spgennard/vscode_cobol
    tags: true
    condition: $TRAVIS_OS_NAME = linux
